### ISSUE TITLE
Some JFlex updates available

### ISSUE THREAD

**Issue by Sciss** [Sciss/sbt-jflex#1]
https://github.com/dlwh/sbt-jflex/commit/8c2e5ea17c858d8bcf509bd2831e76c19a0d0e87

**Comment by FranklinChen** [comment]
Since I'm no longer actively using JFlex, I haven't been following the progress of the SBT plugin. Actually, I'm no longer sure what the authoritative fork is?!

**Comment by Sciss** [comment]
I'm confused, too :) This was just a bookmark to remember that the other fork has been updated.
